### PR TITLE
Build wheels with cibuildwheel

### PR DESCRIPTION
**Pull request by iiSeymour**
Uses cibuildwheel to build Windows, Linux and OSX wheels:

 - `parasail-1.1.19-py2.py3-none-win32.whl`
 - `parasail-1.1.19-py2.py3-none-win_amd64.whl`
 - `parasail-1.1.19-py2.py3-none-macosx_10_6_intel.whl`
 - `parasail-1.1.19-py2.py3-none-manylinux2010_i686.whl`
 - `parasail-1.1.19-py2.py3-none-manylinux2010_x86_64.whl`

Wheels will be uploaded on tags but `TWINE_USERNAME` and `TWINE_PASSWORD` will need setting as secrets.

@jeffdaily is there any reason to use both AppVeyor and Travis?

### CODE REVIEW

**Comment by jeffdaily** [comment]
Perhaps my inexperience is showing.  At the time, I used AppVeyor for various Windows builds.  Travis was used for Linux and OSX.  Did Travis recently support Windows?

**Comment by cjw85** [comment]
I think is was late 2018 when travis started supporting windows.

**Comment by iiSeymour** [comment]
Yes, and the Windows build is nice and fast https://travis-ci.org/iiSeymour/parasail-python

I'll remove AppVeyor in favour of Travis then?

**Comment by iiSeymour** [comment]
What do you think @jeffdaily reckon we could get a 1.1.20 tag?

**Comment by jeffdaily** [comment]
thank you for pinging me on this.  sadly it's necessary these days.  let me see what I can do this afternoon.  thanks.

**Comment by jeffdaily** [comment]
IIRC I've been using appveyor to deploy my pypi binary wheels for Windows, where my script will grab the latest github asset and bundle it into the wheel.  I haven't looked at this PR in detail yet.  Are we still going to have automatic pypi binary wheels for all platforms (perhaps not osx)?

**Comment by iiSeymour** [comment]
Yes, the new travis pipeline builds and deployed binary wheels for Windows, Linux and OSX.

Wheels are built on every commit and only uploaded on tags but you will need to set TWINE_USERNAME and TWINE_PASSWORD under the secrets for this project.

**Comment by iiSeymour** [comment]
You will also want to disable AppVeyor now to stop the failing checks messages due to the lack of a `appveyor.yml`.

**Comment by jeffdaily** [comment]
Disabled the AppVeyor webhook.

**Comment by jeffdaily** [comment]
Trust fall.

**Comment by iiSeymour** [comment]
I did want to enable the test suite but it needs a bit of work. I'd be happy to work a separate merge request if you are interested?

For the `1.1.20` release we will want to upload a `sdist` to PyPI also.

I would recommend locally bumping the version, commit it, tag it, upload the sdist, then push the tag to github and watch the wheels follow 🚀

Finally, this closes #11.

**Comment by jeffdaily** [comment]
Is there an automated way to build and upload a `sdist` to PyPI?

**Comment by iiSeymour** [comment]
Sure, we can just `python setup.py sdist -d wheelhouse` only on the Windows build for example.

**Comment by jeffdaily** [comment]
If you're interested in a test suite, by all means, I'd merge another PR for that.  Sure, I have a few files that might resemble tests if you squint at them a bit, but nothing to be proud of.  That's not to say that I haven't tested things over the years, it just hasn't been automated.  Most of the heavy testing takes place for the C library, and again it is a manual process.  But for the C library I at least confirm all the vectorized implementations get the same answer as the baseline implementation for each algorithm.

**Comment by jeffdaily** [comment]
Tagged v1.1.20.

**Comment by iiSeymour** [comment]
I've created an issue for the test suite and will start working on a PR.

Ah the job failed to upload, I've been using Github Actions for CI recently with uses secrets, sorry @jeffdaily! For Travis we want `TWINE_USERNAME` adding to the global environments in the `.travis.yml` and the `TWINE_PASSWORD` should be set in Travis to a PyPI API token *(which you probably already have?)*.  https://github.com/joerick/cibuildwheel#example-setup

```
env:
  global:
    -TWINE_USERNAME=__token__
    # Note: TWINE_PASSWORD is set to a PyPI API token in Travis setting
```

**Comment by jeffdaily** [comment]
So it's not supposed to be `TWINE_USERNAME=__token__` ?

**Comment by iiSeymour** [comment]
I think `__token__` is just a placeholder to replace your username with.

**Comment by jeffdaily** [comment]
https://pypi.org/help/#apitoken says to set it to __token__.  If I'm reading it correctly.

**Comment by iiSeymour** [comment]
It does, agreed.

**Comment by jeffdaily** [comment]
Seems a bit silly that we've gotten so far only to trip on authentication.  Not quite sure what I did wrong.

**Comment by iiSeymour** [comment]
Totally my fault for giving the wrong instructions 🤦‍♂

After adding the envvar to `.travis.yml` file; either delete and recreate the `1.1.20` tag or bump the version again and create a new tag.

**Comment by iiSeymour** [comment]
I just spotted the upload step is globbing `*.whl` in the wheelhouse directory so it will need changing to pick up the `sdist`.

**Pull request merged**
